name: RuboCop

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: build
      run: |
        sudo apt-get install -y libmysqlclient-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: cop
      run: |
        bundle exec rubocop
